# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cyclefy-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #   PORT: ${{ secrets.PORT }}
    #   UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
    #   APP_NAME: ${{ secrets.APP_NAME }}
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          # npm run railwayTest

      - name: Generate prisma client
        run: |
          npx prisma generate

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_692A1E19B0C64FE0B79A701A7BEB6670 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4A3ABFCC5734050B6D2DB037EDC5BA6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9AE7D001092E439892E67D48274312FB }}

      - name: Run Prisma migration
        run: |
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Prisma Seed
        run: |
          npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cyclefy-backend'
          slot-name: 'Production'
          package: .

          







